### ISSUE TITLE
Just a question. Axis-aligned optimization?

### ISSUE THREAD

**Issue by Llorx** [mfogel/polygon-clipping#103]
I just want to union some axis-aligned rectangles with no floating points. Because this library allows to union weird polygons, seems a bit overpowered for this job. As you made the library, do you happen to have something in mind that will help to get better performance within this scenario? The worse part seems the `checkForConsuming` method, but just need a bit of light here, if possible. I'll do my own fork and tests.

**Comment by mfogel** [comment]
Hi @Llorx , yeah, if your polygons are all integers and then all edges are aligned with the axises, then yes, a simpler implementation of this algorithm would be just fine. A lot of the complication in this project comes from the joys of floating point math.

Another feature that makes the implementation here more complicated is support for operating on N polygons/multipolygons at once, rather than just two polygons. If you are only ever dealing with at most two polygons at once, then there are other JS libs out there that would also probably work and may run faster.

**Comment by Llorx** [comment]
@mfogel I'm having from 2 to hundreds of rectangles actually. WIll check that floating point thingy. Thank you!
