### ISSUE TITLE
Just a question about floating point math...

### ISSUE THREAD

**Issue by bhousel** [mfogel/polygon-clipping#104]
Hey @mfogel, huge thanks for this library!  👏 

I just started using it for a bunch of OpenStreetMap plumbing ([example here](https://ideditor.github.io/location-conflation/)) where JSTS, Turf, and w8r/martinez were causing me issues.

I was wondering about the floating point math... on #103 you said,

> A lot of the complication in this project comes from the joys of floating point math.

If I'm confident that my geo coordinates are within the bounds of [-180,180], and I'm ok with limiting things to 7 digits of floating point precision, is there any benefit to performing the clipping in integer coordinates?

Here's some hacky code that I wrote to convert the GeoJSON coordinate arrays (when I was trying to work around the JSTS, Turf, and w8r/martinez bugs haha), and it didn't seem to hurt anything, but didn't help any either.   Is this nuts?

```js
// Does working with the coordinates *as integers* make clipping work better?
// We expect geo coordinates to be bounded between [-180f, 180f]
// To be safe, consider MAX_INT = 4_294_967_295  per https://stackoverflow.com/a/7179733
// So e.g.   123.4567890 * 1e7 = 1_234_567_890
// 7 digits of float precision in geo coordinates should be plenty for what we are doing.
function _toIntCoords(val) {
  if (typeof val === 'number') return Math.round(val * 1e7);
  else if (Array.isArray(val)) return val.map(_toIntCoords);
  else return val;  // shrug
}

// Put them back to normal geo coords
function _toFloatCoords(val) {
  if (typeof val === 'number') return val / 1e7;
  else if (Array.isArray(val)) return val.map(_toFloatCoords);
  else return val;  // shrug
}
```

**Comment by mfogel** [comment]
Hey @bhousel - good question

Clipping your input coordinates certainly won't hurt. However, it doesn't save you from the joys of floating point issues. Here's an [example test case](https://github.com/mfogel/polygon-clipping/blob/master/test/end-to-end/almost-colinear-segments-but-not-2/args.geojson) where all the input coordinates are 3 decimal places or less but the calculation ends up being sensitive to floating point issues.

There are some instances where clipping your input coordinates will help avoid being sensitive to floating point issues, since it may help 'snap' some of your input coordinates to the same exact point.

Also, if you have just one set of input json and the library is crashing on it, it can help to trim the coordinates because it'll move the points around enough to avoid whatever is causing the lib to crash. But that doesn't appear to apply to your project linked above.

Very cool application!

**Comment by bhousel** [comment]
Thanks for taking the time to answer, and for the awesome library.. 👍
