### ISSUE TITLE
Maximum call stack size exceeded on intersection

### ISSUE THREAD

**Issue by braadworst** [mfogel/polygon-clipping#124]
Hi, trying to intersect two polygons, but get the aforementioned error.

```
polygon-clipping.v0.15.3.js:1110 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Segment.afterState (polygon-clipping.v0.15.3.js:1110)
    at Segment.beforeState (polygon-clipping.v0.15.3.js:1103)
    at Segment.afterState (polygon-clipping.v0.15.3.js:1111)
    at Segment.beforeState (polygon-clipping.v0.15.3.js:1103)
    at Segment.afterState (polygon-clipping.v0.15.3.js:1111)
    at Segment.beforeState (polygon-clipping.v0.15.3.js:1103)
    at Segment.afterState (polygon-clipping.v0.15.3.js:1111)
    at Segment.beforeState (polygon-clipping.v0.15.3.js:1103)
    at Segment.afterState (polygon-clipping.v0.15.3.js:1111)
    at Segment.beforeState (polygon-clipping.v0.15.3.js:1103)
```

I've included the files that I was working with
[geojson.zip](https://github.com/mfogel/polygon-clipping/files/6875045/geojson.zip)

Am I using it in the wrong way? I didn't see the same issue yet hence I made a new ticket for it

**Comment by Athorcis** [comment]
The problem seems to happen when the RingOut object is built, I found a case where one of the segments has itself as the previous segment
![Screenshot_1](https://user-images.githubusercontent.com/4405110/139878538-35b4db01-7744-4ab9-bff4-6f1e10dc7ef9.jpg)
but I'm not sure that add a check to that line (https://github.com/mfogel/polygon-clipping/blob/203699f5f39fedbdaa1b44ed2ad75f79309d8362/src/sweep-line.js#L131) would suffice

**Comment by macksal** [comment]
@Athorcis I get the same issue, and it seems to propagate from earlier in the code.

At this line: [https://github.com/mfogel/polygon-clipping/blob/203699f5f39fedbdaa1b44ed2ad75f79309d8362/src/sweep-line.js#L53](https://github.com/mfogel/polygon-clipping/blob/203699f5f39fedbdaa1b44ed2ad75f79309d8362/src/sweep-line.js#L53)

I get these evaluations:

```
> node.key == this.tree.prev(node).key
true
> node == this.tree.prev(node)
false
```

So it looks like there are two nodes in the splay tree with the same node. I don't know enough about the algorithm to know if this should be avoided or not, but I will read the paper. If this is the triggering condition, it seems easy to just use `tree.add` and not `tree.insert` since insert allows for two nodes with the same key.
