### ISSUE TITLE
About floating point...

### ISSUE THREAD

**Issue by erikh2000** [mfogel/polygon-clipping#13]
Mike, I was surprised that squaring `EPSILON` and `(a-b)` is *much* faster than calling `Math.abs()`. So I changed my floating point comparison code in my project to match how you are doing it.

It does look like you can get an optimization by reusing your EPSILON_SQ value on line 19 instead of squaring again here.

Finally, I don't understand this block...
```
// check if they're both 0
    if (-Number.EPSILON < a && a < Number.EPSILON) {
      if (-Number.EPSILON < b && b < Number.EPSILON) {
        continue
      }
    }
```

Did you find it was a necessary special case? In my benchmarks, the comparison for passing a=0, b=0 was actually *slower* with this code in place. Of course, all my timing is just in one browser/environment. So maybe that is a fluke.

**Comment by erikh2000** [comment]
Also, I think you may be missing an IE polyfill for Number.EPSILON.

**Comment by mfogel** [comment]
@erikh2000 thanks for catching those things - using EPSILON_SQ more and the IE polyfill. The commit linked above should be fix those issues up.

The code block you have quoted about is necessary because, well, really because without it at least one of the tests fails. One of the end-to-end tests gets stuck in an infinite loop. Not sure which.

Without that block, you can have a situation where:

```js
flp.cmp(0, valueCloseToZero) // 0
flp.cmp(0, anotherValueCloseToZero) // 0
flp.cmp(valueCloseToZero, anotherValueCloseToZero) // 1 or -1
```

If that block above *is* included, then the last comparison will be

```js
flp.cmp(valueCloseToZero, anotherValueCloseToZero) // 0
```

So basically this block makes equality associative for values close to 0.

Now, I'm pulling this from memory, but as I recall without this block the sorting of the Sweep Event priority queue and the sorting of the Segments in the Sweep Line binary tree gets messed up. If equality is not associative for values close to 0, the sorting in those data structures won't be consistent, and it is possible to add values to these data structures and then not be able to find them in there later.

Of course, for values that aren't close to zero - close to another value, say 1 - equality in this floating point lib is *not* strictly associative. (Ex: `1`, `1 + Number.EPSILON * 3 / 4`, `1 - Number.EPSILON * 3 / 4`) But that doesn't cause problems for the algorithm.

**Comment by mfogel** [comment]
I just noticed you're referencing the block in `cmpPoints()` rather than in `cmp()`. The same logic all holds true in `cmpPoints()` - that basically just has an inlined version of `cmp()`, for performance.

**Comment by erikh2000** [comment]
Ah, great explanation on the zero-check block. I may do something similar in my project.
