### ISSUE TITLE
coordinates with z-value fail validation

### ISSUE THREAD

**Issue by kriscarle** [mfogel/polygon-clipping#23]
This line checks that the array length is 2 and fails if there is a third z coordinate https://github.com/mfogel/polygon-clipping/blob/master/src/clean-input.js#L27

Happy to submit a PR to allow a length of 2 or 3 on this line, but I'm not familiar enough with code yet to know if that will cause other problems? The z values are not needed in my case, just sometimes present in data my users upload. Just wanted to raise this here in case it is a quick fix.

Also thanks for putting this library together, super helpful!

**Comment by mfogel** [comment]
Hi @kriscarle - not really a quick fix to carry through z-values. There would be some tricky situations to handle. Points are sometimes created (intersection between two line segments) and sometimes combined (parallel overlapping segments). Not impossible, but those cases would need to be handled. I would also be concerned about possible performance impacts of carrying around a third coordinate on every point.

And as far as just dropping the z-values - my preference is that the library raise a loud, clear error rather than silently dropping the extra coordinates.

If you don't need the z-values, would it work if you did a pass over the coordinates and just dropped the z-values before passing the polygons to this lib?

**Comment by kriscarle** [comment]
Hi @mfogel yes, I'm now just dropping the z values before handing to this lib. It doesn't seem worth trying to support pass through, though a "z-values not supported" error message would be helpful. Thanks!

**Comment by mfogel** [comment]
Yeah, that sounds like a good idea, easy to raise a better error message there

**Comment by cyrilchapon** [comment]
Hey,

From a spec point of view :

>  A position is an array of numbers.  There MUST be two or more
   elements.  The first two elements are longitude and latitude, or
   easting and northing, precisely in that order and using decimal
   numbers.  Altitude or elevation MAY be included as an optional third
   element.

> Implementations SHOULD NOT extend positions beyond three elements
   because the semantics of extra elements are unspecified and
   ambiguous.  Historically, some implementations have used a fourth
   element to carry a linear referencing measure (sometimes denoted as
   "M") or a numerical timestamp, but in most situations a parser will
   not be able to properly interpret these values.  The interpretation
   and meaning of additional elements is beyond the scope of this
   specification, and additional elements MAY be ignored by parsers.

It therefore "might" be sometimes more arguments than even 3, so the error message should take that in consideration IMHO

**Comment by mfogel** [comment]
@cyrilchapon good point, thanks for the heads up

The commit I just dropped on master improves the error message in the more-than-two-coordinates-input-polygons case, with some test cases to ensure it works.
