### ISSUE TITLE
error intersecting polygons

### ISSUE THREAD

**Issue by jomel** [mfogel/polygon-clipping#37]
see gist for polygons in question:
https://gist.github.com/jomel/45d2c23bc7d3b83143af18fb8ce1312a

when trying to run intersection()
I get :
```
Error: Unable to complete output ring starting at [0.523657, 51.281218]. Last matching segment found ends at  [0.5239850000000017, 51.281651].
    at Function.factory (webpack://polygon-clipping/./src/geom-out.js?:52:21)
    at doIt (webpack://polygon-clipping/./src/index.js?:81:34)
    at intersection (webpack://polygon-clipping/./main.js?:30:28)
...
```

I don't see anything odd about my geometries...

**Comment by mfogel** [comment]
Thanks for the bug report @jomel 

This is a simplified version of that geometry that still triggers the bug (by performing an `intersection()` on the Features in the FeatureCollection below):

```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [0.5242, 51.2815],
            [0.52406, 51.281726],
            [0.523787, 51.281453],
            [0.5242, 51.2815]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [0.5241, 51.2816],
            [0.52401, 51.2817],
            [0.523985, 51.281651],
            [0.5241, 51.2816]
          ]
        ]
      }
    }
  ]
}
```

In this simplified geometry it looks like the problem is occurring because on of the vertices (`[0.523985, 51.281651]`) is almost-just-barely-not-quite on one of the line segments (`[0.523787, 51.281453] <-> [0.52406, 51.281726]`). Basically sometimes the algorithm thinks the vertex intersects that line segment, and sometimes it thinks it doesn't. That inconsistency leads to the error.

I'll see if I can figure out a fix.

**Comment by mfogel** [comment]
I've verified that the latest on master now successfully processes the coordinates linked to and quoted in this bug.
