### ISSUE TITLE
Error creating unnecessary hole on union

### ISSUE THREAD

**Issue by rowanwins** [mfogel/polygon-clipping#57]
Hi @mfogel 

So I've encountered a new issue when union-ing a single polygon.

[The polygon](https://gist.github.com/rowanwins/2523d68c242d0569df35b024edc40357) crosses over itself and should result in a single hole.

However it is [resulting in two holes](https://gist.github.com/rowanwins/eeecbac91cd5fd1e0384e534ffaa0e7c), the second of which is not required.

Grrr don't you hate edge cases :)

**Comment by mfogel** [comment]
Hi @rowanwins thanks for bug report

Are you thinking it would better for the output polygon to have one bow-tie shaped hole, instead of two holes that touch at one point? Right now the logic that forms the output favors making two rings instead of one ring that self-intersects. Is that what you're referring to or am I on the wrong track?

**Comment by rowanwins** [comment]
This is what I would've [expected](https://gist.github.com/rowanwins/180858e23074a1e8b3817f6a78ba8579) to get back, hope that helps clarify.

**Comment by rowanwins** [comment]
As some bonus context, I've been [writing a buffer module](https://rowanwins.github.io/geojson-buffer/index.html), under the hood I'm using `polygon-clipping` to check for overlaps at the end. You can see the sort of error that I'm getting with the line feature that gets buffered.

**Comment by mfogel** [comment]
Ah, gotcha, I see what you mean. Yeah I can see how the current behavior isn't right for that situation.

I'm trying to think of a counter example of where the current behavior would be the desired behavior... so far no success.

**Comment by rowanwins** [comment]
Yeah I suspect the proposed is more common, I can't think of a case where you'd want to retain those holes.

As an aside one thing I've [done elsewhere is setup tests](https://github.com/DenisCarriere/boolean-shapely/blob/master/index.js) which run against more established spatial libs, in particular `shapely`, which is a python lib. This was helpful for testing the outputs we were generating compared to a more established lib. If that's of any interest let me know.

**Comment by mfogel** [comment]
I think this is a case of where the [non-zero rule](https://en.wikipedia.org/wiki/Nonzero-rule) and the [even-odd rule](https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule) differ. Basically, I think to count this area as inside the polygon, this lib should swtich from using the even-odd rule to the non-zero rule. Which sounds ok to me, I would agree that I think most if not all users of the lib would expect that area to be filled in your example.

I'd consider this to be a backwards-incompatible change since it is changing behavior that is documented in the README.

**Comment by mfogel** [comment]
The SVG standard [defaults to non-zero rule for filling polygons](https://www.w3.org/TR/SVG/painting.html#WindingRule) as well, this lib should probably mirror that behavior as this ticket suggests

**Comment by mfogel** [comment]
work progressing on this branch: https://github.com/mfogel/polygon-clipping/tree/feature/non-zero-rule
