### ISSUE TITLE
Try out robust-predicates for vector math

### ISSUE THREAD

**Issue by mfogel** [mfogel/polygon-clipping#92]
As pointed out by @rowanwins in #89, this library might benefit by making use of the lib [robust-predicates](https://github.com/mourner/robust-predicates)

The vector math in `src/vector.js` in particular could certainly use the `orient2d()` method from robust-predicates. There may also be other opportunities to make use of the lib beyond that.

I have a lot of trust in the test suite this project has accumulated over the years, so if `npm test` passes on a PR - that generally means the change is safe to merge. `npm run bench` can be used to see what affect changes have on performance.

**Comment by rowanwins** [comment]
Finally returning to this! 

So in `src/vector.js` you can replace the existing `compareVectorAngles` function with something like
````
export const compareVectorAngles = (basePt, endPt1, endPt2) => {
  const res = orient2d(basePt.x, basePt.y, endPt1.x, endPt1.y, endPt2.x, endPt2.y, )
  if (res > 0) return -1
  if (res < 0) return 1
  return 0
````

This results in one failing unit test for [almost equal points](https://github.com/mfogel/polygon-clipping/blob/master/test/geom-out.test.js#L352), presumably because the epsilon test is being bypassed in `src/flp` now, I'm not quite suer how you'd refactor the above to capture that same thing - any ideas @mfogel ?

13 end-to-end tests fail now, I'm guessing mostly because of the above...
